# Minecraft 1.21.2-1.21.4 / NeoForge. Java 21.
deps.neoforge = 21.4.157
meta.mc_range_maven = [1.21.2,1.21.5)
meta.mc_versions = 1.21.2, 1.21.3, 1.21.4
meta.loader_range = [21.2,)
meta.javafml_range = [4,)

# 1.21.2 and 1.21.3 are 42; 1.21.4 is 46.
meta.pack_format = 46
meta.pack_formats = 42, 46

meta.src_era = 1.21.2
